### ISSUE TITLE
Typescript compilation error "TS1005: ',' expected" with Typescript < 4.0

### ISSUE THREAD

**Issue by setvik** [codsen/codsen#11]
**Package's name**
All

**Describe the bug**
Only compiles with Typescript 4.0+ b/c of 4.0+ only usage of labeled tuple elements:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#labeled-tuple-elements

**To Reproduce**
1. Clone project
2. Compile with Typescript < 4.0 (e.g. 3.8.x)
4. Typescript compilation errors out with the `error TS1005: ',' expected.` error similar to that in screenshot below

<img width="872" alt="Screen Shot 2021-05-07 at 3 34 39 PM" src="https://user-images.githubusercontent.com/231964/117407629-c7883d00-af49-11eb-9e2f-3d96d539c7e6.png">

**Comment by revelt** [comment]
Hi Stein! Thank you for raising it and sorry for all this situation.

I generate all type definitions automatically, using `rollup-plugin-dts` and it must tap the latest and greatest `"typescript": "^4.2.4"`, as requested by package.json.

I see few possibilities to solve this, I need your opinion.

- we can downgrade to 3.x everything in the monorepo so generated `.d.ts` will be most compatible
- we can find ways to generate and automatically bundle 4.x `.d.ts`, but separately, build 3.x `.d.ts` and instruct people on 3.x TS to manually override them. For example, package would have `types` folder for 4.x and `types-v3` for 3.x
- we can try to force `rollup-plugin-dts` to generate defs in older, 3.x compatible-shape, while it is still reading TS sources in 4.x

Which way do you think is the most sensible?
If we found ways to generate and separately bundle 3.x `.d.t.s`, would it be practical for you to override your TS setup and consume those 3.x defs?

Again, sorry for the trouble, I'll do my best to solve this. People already complained (#9) about 4.x defs, so this issue won't go away easily.

Additionally, I think readme needs more explanations, whichever solution we choose.

**Comment by revelt** [comment]
Typescript v4 is two years old now, I'll close the ticket
